### ISSUE TITLE
release-charm: The charm release fails if charm uses single charmcraft.yaml instead of metadata.yaml

### ISSUE THREAD

**Issue by theoctober19th** [canonical/data-platform-workflows#169]
In the newer charm SDK versions, it is possible to merge yaml files like `metadata.yaml`, `actions.yaml`, etc. to a single `charmcraft.yaml` file. However, if a charm uses single `charmcraft.yaml` pattern, the release is blocked because the release workflow logic tries to look for `metadata.yaml` file which does not exist in the first place.

Here is the line which contains that logic:
https://github.com/canonical/data-platform-workflows/blob/main/python/cli/data_platform_workflows_cli/craft_tools/release.py#L160C37-L160C46

Expected behavior:
The release should work fine even on using a single charmcraft.yaml file for all metadata (maybe it can use charmcraft.yaml first and then metadata.yaml as a fallback or the other way around).

Logs from Actions:
```
Run release-charm --charm-directory='.' --channel='latest/edge'
INFO:root:Uploading charm_file=PosixPath('kyuubi-k8s_ubuntu-22.04-amd[6](https://github.com/canonical/kyuubi-k8s-operator/actions/runs/8781656696/job/24095095011#step:7:7)4.charm')
INFO:root:Uploaded charm revision=1
Traceback (most recent call last):
  File "/opt/pipx_bin/release-charm", line [8](https://github.com/canonical/kyuubi-k8s-operator/actions/runs/8781656696/job/24095095011#step:7:9), in <module>
    sys.exit(main())
  File "/opt/pipx/venvs/data-platform-workflows-cli/lib/python3.10/site-packages/data_platform_workflows_cli/release_charm.py", line 54, in main
    metadata_file = yaml.safe_load((charm_directory / "metadata.yaml").read_text())
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 111[9](https://github.com/canonical/kyuubi-k8s-operator/actions/runs/8781656696/job/24095095011#step:7:10), in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'metadata.yaml'
```

**Comment by theoctober19th** [comment]
I faced this while releasing the [Apache Kyuubi charm](https://github.com/canonical/kyuubi-k8s-operator). I believe the enchancement can be done in a backward-compatible way such that charmcraft.yaml is looked only when metadata.yaml file is not found. However, this is not something that is urgent to me and I am happy to refactor `charmcraft.yaml` into multiple files and move forward :)
